#!/bin/bash

check=$(npm run typecheck)
result=$?

if [[ ${result} -ne 0 ]]; then
  echo "Cannot commit: Type check failed"
  exit 1
fi

fmt=$(./node_modules/.bin/eslint .)
result=$?

if [[ ${result} -ne 0 ]]; then
  echo "Cannot commit: Code is not formatted"
  exit 1
fi

exit 0
